version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
        # Here you can change the mongo connection string
      - DEV_DATABASE_URL=
    ports:
      - 3001:3001
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      
 